### ISSUE TITLE
CAN Interface

### ISSUE THREAD

**Issue by kameev** [taHC81/Eltek-Flatpack2-ESPhome#3]
Thank you for that grate project! 
Everything went smooth!

Just one remark, i build it up like it is on the picture, but i had to change the CAN Interface in the yaml.

rx_pin: GPIO19
tx_pin: GPIO18  

to

rx_pin: GPIO18
tx_pin: GPIO19

Just in case someone faces a simular issue.

**Comment by taHC81** [comment]
Thanks for this!
